version: '1.0'
mode: parallel
stages:
- clone
- build

steps:
  main_clone:
    title: Clone main repository
    type: git-clone
    stage: clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}

  build_docker:
    type: build
    stage: build
    title: Build release image containing binary
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: ${{CF_BRANCH}}
    when:
      steps:
      - name: main_clone
        on:
        - success
